### ISSUE TITLE
Unavailibility of the lab link

### ISSUE THREAD

**Issue by pushpdeep** [Virtual-Labs/engineers-forum#144] opened 2015-06-09 06:55 UTC
The Urban Transportation lab was previously available on this url
http://deploy.virtual-labs.ac.in/labs/civil13

right now its not accessible please get back the link working .

Thanks

**Comment by MSSoumya** [comment] 2015-06-11 06:18
We were decommissioning deploy so we had to redeploy the lab on a separate container. As we did not know the process for deploying a lab with database dependency we sent out a mail (sub:Process for hosting civil13 lab, Date: April 17th) requesting the steps to do so. We did not receive a response on how it should be done, so now deploy is decommissioned and the lab was not redeployed.

**Comment by ecthiender** [comment] 2015-06-11 06:25
The lab is available at: http://civil13-iitb.virtual-labs.ac.in/index.php , but it is not deployed correctly.
Links at vlab.co.in is also not updated as the lab is not deployed correctly.

**Comment by MSSoumya** [comment] 2015-06-11 09:20
Also, in the last mail in that chain I remember you mention that the hosting be suspended till the lab gets reviewed by experts. So now if the lab is reviewed please provide us the steps to deploy this lab.

**Comment by pushpdeep** [comment] 2015-06-11 10:47
Sure soumya
On Jun 11, 2015 2:50 PM, "MSSoumya" <notifications@github.com> wrote:
>
> Also, in the last mail in that chain I remember you mention that the
hosting be suspended till the lab gets reviewed by experts. So now if the
lab is reviewed please provide us the steps to deploy this lab.

**Comment by sanchita-dixit** [comment] 2015-07-21 06:19
@pushpdeep Any updates on this.

**Comment by pushpdeep** [comment] 2015-07-21 06:21
Dear Soumya,
there are some issues with the simulator, the development team is fixing
that.
shall be pushing it to git after that

Thanks
Regards

*---Pushpdeep.Mishra*


*Tuberculosis Daily http://bit.ly/iCACcq <http://bit.ly/iCACcq>*

**Comment by ecthiender** [comment] 2015-07-22 05:10
Pushpdeep, may I close this issue ("Unavailability of the lab link") then?

Once, the lab is ready, you can raise a "request for hosting" ?

**Comment by pushpdeep** [comment] 2015-07-22 07:04
sure.
you can close.

thanks


*---Pushpdeep.Mishra*


*Tuberculosis Daily http://bit.ly/iCACcq <http://bit.ly/iCACcq>*

**Comment by sanchita-dixit** [comment] 2015-07-27 09:51
@pushpdeep @ecthiender @MSSoumya Since there was a consensus on closing this issue, I am closing it.

**Closed by sanchita-dixit** 2015-07-27 09:51 UTC
Labels: bug, help wanted

**Comment by ecthiender** [comment] 2015-07-27 09:56
There was consensus. On 22nd July, Pushpdeep confirmed to close this
issue!!!
