### ISSUE TITLE
Phase II Lab/Experiment Hosting/Re-hosting Request for Strength of Materials lab -  NITK Surathkal

### ISSUE THREAD

**Issue by AkshayaAcharya** [virtual-labs/engineers-forum#490] opened 2018-09-18 12:08 UTC
The contents of **strength of materials lab** has been updated.

Please find the below link.

[https://github.com/virtual-labs/strength-of-materials-nitk.git](https://github.com/virtual-labs/strength-of-materials-nitk)

Please update the contents of strength of materials lab http://sm-nitk.vlabs.ac.in/ on vlab.co.in under Civil Engineering and also under NITK Labs list.

Thank You
@kraghupathi

**Comment by sravanthimodepu** [comment] 2018-09-19 05:16
Working on this will get back to you soon.

**Comment by sravanthimodepu** [comment] 2018-09-19 10:58
@AkshayaAcharya 

Updated the Strength of materials lab sources, please check the lab at [sm-nitk.vlabs.a.cin](http://sm-nitk.vlabs.ac.in).

Send a mail to Sanjeet to update the Strength of materials lab on vlab.co.in under Civil Engineering and in the NITK Labs list.

**Comment by AkshayaAcharya** [comment] 2018-09-20 08:34
@kraghupathi @sravanthimodepu 
  
Some of the images of **strength of materials lab** are not visible in the link [http://sm-nitk.vlabs.ac.in/](http://sm-nitk.vlabs.ac.in/) 
  
I have updated the contents again and below is the Github URL of strength of materials lab.
[https://github.com/virtual-labs/strength-of-materials-nitk.git](https://github.com/virtual-labs/strength-of-materials-nitk.git)
 
Can you please update it again.

Thank You

**Comment by AkshayaAcharya** [comment] 2018-09-20 11:18
@sravanthimodepu 
 
I have checked the Strength of Materials Lab link [http://sm-nitk.vlabs.ac.in/](http://sm-nitk.vlabs.ac.in/).
  
I am getting following error in simulation of one of the experiments **Bending Test on Mild Steel**.This is the link to that experiment. [http://sm-nitk.vlabs.ac.in/exp11/index.html#](http://sm-nitk.vlabs.ac.in/exp11/index.html#)

Screenshot of that error attached below.

![smerror](https://user-images.githubusercontent.com/24836968/45814831-86897e80-bcf4-11e8-8b75-0fc255c72e85.PNG)

Can you please check it.

Thank Tou

**Comment by sravanthimodepu** [comment] 2018-09-20 12:39
@AkshayaAcharya 

This might be an issue with the path or a broken link( /sm-nitk/images/BendingMS/bendingMS.html) in the respective file. Please fix this issue.

**Comment by AkshayaAcharya** [comment] 2018-09-21 07:30
@sravanthimodepu 

Path to the file is given as (. ./images/BendingMS/bendingMS.html) in the code and the file is loading when I run it locally.
So can you please suggest me a solution to fix this issue.

Thank You

**Comment by AkshayaAcharya** [comment] 2018-09-24 04:54
@sravanthimodepu 

I have done some changes in the code.I have updated the content to Github.

Following is the Github URL.
[https://github.com/virtual-labs/strength-of-materials-nitk.git](https://github.com/virtual-labs/strength-of-materials-nitk.git).

Please update the contents to the link [http://sm-nitk.vlabs.ac.in/](http://sm-nitk.vlabs.ac.in/)

Thank You

**Comment by vleadadmin** [comment] 2018-09-24 05:54
@AkshayaAcharya 

Updated the sources of [http://sm-nitk.vlabs.ac.in](http://sm-nitk.vlabs.ac.in). Please check, and confirm.

**Comment by sravanthimodepu** [comment] 2018-09-24 05:55
@AkshayaAcharya

Updated the sources of http://sm-nitk.vlabs.ac.in. Please check, and confirm.

**Comment by AkshayaAcharya** [comment] 2018-09-24 06:51
@vleadadmin @sravanthimodepu 

Contents are updated.

Thank You

**Comment by AkshayaAcharya** [comment] 2020-02-13 05:54
@vleadadmin @sravanthimodepu 

We are facing some issues with the [Strength of Materials Lab](http://sm-nitk.vlabs.ac.in).

Below are the screenshots of the errors we are getting now and were not there before.
1. Error in **Link to Experiments**. Link is not clickable.
![linkerror](https://user-images.githubusercontent.com/24836968/74404064-70cbaa80-4e4f-11ea-9651-3b59bb4f5428.png)

2. Error in observation page of simulator. Below error can be found in simulation of 5 experiments and are listed below.
      1. [Tensile Test on Mild Steel ](http://sm-nitk.vlabs.ac.in/exp13/index.html#)
      2. [Tensile Test on Cast Iron ](http://sm-nitk.vlabs.ac.in/exp14/index.html#)
      3. [Compression Test on Mild Steel](http://sm-nitk.vlabs.ac.in/exp15/index.html#)
      4. [Compression Test on Cast Iron ](http://sm-nitk.vlabs.ac.in/exp16/index.html#)
      5. [Torsion Test on Mild Steel ](http://sm-nitk.vlabs.ac.in/exp19/index.html#)

![observation](https://user-images.githubusercontent.com/24836968/74404656-277c5a80-4e51-11ea-9822-2101ea2a8930.png)

Tables in Observation screen are overlapping. 

Last updated Github url for SOM lab is: [https://github.com/virtual-labs/strength-of-materials-nitk.git](https://github.com/virtual-labs/strength-of-materials-nitk.git)
Can you please check the issues.

Thank You

**Comment by priya100raman** [comment] 2020-02-13 06:56
@AkshayaAcharya , we are looking into it. We will give you an update shortly.

**Comment by raj-vlabs** [comment] 2020-02-13 07:22
Hi Akshaya,
This is how the file looked on the 24th Sep 2018 right after your commit.

https://github.com/virtual-labs/strength-of-materials-nitk/blob/212100b7a9b83185b8a81b18f475da767204567c/src/lab/images/Torsionms/index.html

As you can see in element with id canvas7 that the tables are positioned absolute and are given the top and right margins of 50px,50px and 0px,100px. As the vertical size of the first table is larger than 50px, they are bound to overlap. For the tables to avoid overlapping, you need to fix their location on the page.
We are still looking into the issue with the characters around "list of experiments" on the introduction page. We will update you shortly on that.

**Comment by AkshayaAcharya** [comment] 2020-02-13 09:18
Thank you @raj-vlabs 

Table issue solved in only Torsion Experiment: [Torsion Test on Mild Steel ](http://sm-nitk.vlabs.ac.in/exp19/index.html#)

But remaining experiments have same table overlapping issue. 
[Tensile Test on Mild Steel](http://sm-nitk.vlabs.ac.in/exp13/index.html)
[Tensile Test on Cast Iron](http://sm-nitk.vlabs.ac.in/exp14/index.html)
[Compression Test on Mild Steel](http://sm-nitk.vlabs.ac.in/exp15/index.html)
[Compression Test on Cast Iron ](http://sm-nitk.vlabs.ac.in/exp16/index.html)

**Comment by raj-vlabs** [comment] 2020-02-13 10:23
Hi Akshaya,
Could you please verify if all of them are resolved now?

**Comment by AkshayaAcharya** [comment] 2020-02-13 13:09
@raj-vlabs 

All the simulations are working correctly now.

Thank you

**Comment by AkshayaAcharya** [comment] 2020-05-30 08:13
# _Hosting Request_

Request to update the contents of the Strength of Materials Lab ( http://sm-nitk.vlabs.ac.in/ ) in vlab.co.in under Civil Engineering domain and also under the NITK Labs list.
Both fields are mandatory.

1. Registration request: [https://github.com/virtual-labs/strength-of-materials-nitk.git](https://github.com/virtual-labs/strength-of-materials-nitk.git)
2. Tag: v1.1.0

Thank you

@sravanthimodepu @raj-vlabs

**Comment by sravanthimodepu** [comment] 2020-06-01 07:12
@AkshayaAcharya

Updated the content in the lab, please check and confirm.

**Comment by AkshayaAcharya** [comment] 2020-06-01 08:50
@sravanthimodepu 

Changes are not updated in this link: http://sm-nitk.vlabs.ac.in/

Thank you

**Comment by sravanthimodepu** [comment] 2020-06-01 10:07
@AkshayaAcharya

Updated the content in the lab, please check and let me know

**Comment by AkshayaAcharya** [comment] 2020-06-01 11:27
@sravanthimodepu 

In the simulation of all 3 direct shear experiments, I am not able to see the observation and calculation part. Screenshots of the error are attached below.

![obsstep1](https://user-images.githubusercontent.com/24836968/83403821-00a95a80-a427-11ea-8ffa-055ea9ef33a1.png)

After entering values and click on the check button. I am supposed to get the below result.
![obsOutput](https://user-images.githubusercontent.com/24836968/83403981-6269c480-a427-11ea-8e98-c3d92496059f.png)


But I am getting a blank page like below.

![obserror](https://user-images.githubusercontent.com/24836968/83404098-99d87100-a427-11ea-9dbd-12af6051e260.png)

Can you please let me know about the issue? If there are any changes to be made in my code, please let me know.

Links for the 3 experiments are given below: 

Direct Shear Test on Mild Steel Rod: http://sm-nitk.vlabs.ac.in/exp7/index.html
Direct Shear Test on Timber Specimen: http://sm-nitk.vlabs.ac.in/exp8/index.html
Direct Shear Test on Mild Steel Plate: http://sm-nitk.vlabs.ac.in/exp9/index.html


Thank you

**Comment by sravanthimodepu** [comment] 2020-06-01 14:11
@AkshayaAcharya 

The issue is in the source code which you have to fix in the experiments.
Please fix the issue and let me know, then I'll host the lab again

**Comment by raj-vlabs** [comment] 2020-06-02 06:26
@AkshayaAcharya
@sravanthimodepu has found some bugs in your code. Please work with her to resolve them and get the lab rehosted.

**Comment by sravanthimodepu** [comment] 2020-06-02 06:41
@AkshayaAcharya 

Reverted back the lab with previous sources yesterday, I will update the lab after resolving the current issue.

**Comment by AkshayaAcharya** [comment] 2020-06-02 08:41
@sravanthimodepu

I have done some changes to the code. I have updated the content to Github.

The following is the Github URL.
https://github.com/virtual-labs/strength-of-materials-nitk.git.

Please update the contents to the link http://sm-nitk.vlabs.ac.in/

Thank You

**Comment by sravanthimodepu** [comment] 2020-06-02 09:37
@AkshayaAcharya 

Updated the sources at http://sm-nitk.vlabs.ac.in/, please check and confirm.

Also I found a bug in the home page oof the lab instead of "" it is displaying a special character at "Click on âList of experimentsâ to see which are the labs available to explore"
Please find the screenshot below
![Screenshot from 2020-06-02 15:04:52](https://user-images.githubusercontent.com/11156924/83504913-b71e4580-a4e2-11ea-909a-236e45e6296e.png)

**Comment by AkshayaAcharya** [comment] 2020-06-02 11:21
@sravanthimodepu

There were bugs in the source code, So I have done some changes and updated to the following Github Repo: 

https://github.com/virtual-labs/strength-of-materials-nitk.git.

Please update the contents to the link http://sm-nitk.vlabs.ac.in/

Thank You

**Comment by sravanthimodepu** [comment] 2020-06-02 11:32
@AkshayaAcharya 

Updated the contents of the lab at http://sm-nitk.vlabs.ac.in/. please check and confirm

Also create a tag for the updated content.

**Comment by AkshayaAcharya** [comment] 2020-06-03 09:59
@sravanthimodepu

I apologize for the multiple requests for lab hosting.

There was an issue in one of the experiments which I have corrected now and updated to the repo.

Repo Link: https://github.com/virtual-labs/strength-of-materials-nitk

Commit Version: v1.1.1

I would request you to rehost the link http://sm-nitk.vlabs.ac.in/


Thank you

**Comment by sravanthimodepu** [comment] 2020-06-03 10:22
@AkshayaAcharya 

Hosted the lab with the above mentioned commit, please check the lab http://sm-nitk.vlabs.ac.in/

**Comment by AkshayaAcharya** [comment] 2020-06-03 11:01
@sravanthimodepu

Contents are updated. Thank you

**Comment by AkshayaAcharya** [comment] 2020-09-07 12:07
@sravanthimodepu @priya100raman 

Contents of Strength of Materials Lab has been uploaded. Below is repository link:
[https://github.com/virtual-labs/strength-of-materials-nitk.git](https://github.com/virtual-labs/strength-of-materials-nitk.git)

Commit Version: v1.1.2

I would request you to upload the new content and rehost the link [http://sm-nitk.vlabs.ac.in/](http://sm-nitk.vlabs.ac.in/)

Thank you

**Comment by sravanthimodepu** [comment] 2020-09-08 04:46
@AkshayaAcharya 

Hosted URL of Lab: http://sm-nitk.vlabs.ac.in
Branch: Master
Tag: v1.1.2

Please check and  confirm

**Comment by AkshayaAcharya** [comment] 2020-09-08 05:26
@sravanthimodepu 

Contents in the link [http://sm-nitk.vlabs.ac.in](http://sm-nitk.vlabs.ac.in) are not updated.

**Comment by sravanthimodepu** [comment] 2020-09-08 05:39
@AkshayaAcharya 

Please check now and confirm

**Comment by AkshayaAcharya** [comment] 2020-09-08 06:06
@sravanthimodepu 

No contents are not updated.

Updated Commit Version is: v1.1.2

**Comment by sravanthimodepu** [comment] 2020-09-08 06:34
@AkshayaAcharya 

Could you please clear the cache in the browser or test the lab on private browser.

**Comment by AkshayaAcharya** [comment] 2020-09-08 09:09
@sravanthimodepu 

Contents are updated.

Thank you

**Comment by pavanchow** [comment] 2020-09-16 11:39
(Re)deployed lab with analytics code snippet. 
Hosted **URL** of Lab: http://sm-nitk.vlabs.ac.in
Branch: Master
Tag: v1.1.2

**Comment by AkshayaAcharya** [comment] 2020-10-12 17:28
@sravanthimodepu

Contents of Strength of Materials Lab has been uploaded. Below is repository link:
[https://github.com/virtual-labs/strength-of-materials-nitk.git](https://github.com/virtual-labs/strength-of-materials-nitk.git)

Commit Version: v1.1.3

I would request you to upload the new content and rehost the link [http://sm-nitk.vlabs.ac.in/](http://sm-nitk.vlabs.ac.in/)

Thank you

**Comment by pavanchow** [comment] 2020-10-12 18:09
@AkshayaAcharya 
Hosted URL of Lab: http://sm-nitk.vlabs.ac.in
Branch: Master
Tag: v1.1.3

Please check and confirm.

**Comment by AkshayaAcharya** [comment] 2020-10-14 03:30
@pavanchow 

Contents of Strength of Materials Lab has been uploaded. Below is repository link:
https://github.com/virtual-labs/strength-of-materials-nitk.git

Commit Version: v1.1.4

I would request you to upload the new content and re-host the link http://sm-nitk.vlabs.ac.in/

Thank you

**Comment by pavanchow** [comment] 2020-10-14 04:17
@AkshayaAcharya 
Hosted URL of Lab: http://sm-nitk.vlabs.ac.in
Branch: Master
Tag: v1.1.4

**Please check and confirm** whether code is reflecting in the production.

**Comment by AkshayaAcharya** [comment] 2020-10-14 04:35
@pavanchow 
Contents are updated.

Thank you

**Comment by raj-vlabs** [comment] 2020-10-14 05:21
@AkshayaAcharya It is imperative that you update us in case you see any discrepancies or bugs in the hosting. That will take one hosting request to its logical conclusion.
We did not receive any response for v1.1.3 after hosting.

Also @pavanchow is our hosting engineer going forward. Please continue to mention him in the hosting requests you raise.

best regards
raj

**Comment by AkshayaAcharya** [comment] 2020-10-14 05:31
@raj-vlabs 

Okay Sir. Contents of v1.1.3 were updated properly and sorry for not responding on the hosting.

There were still modifications in the contents and requested for v1.1.4 hosting. Now the the contents are updated properly. 

We request @pavanchow regarding hosting from now on.


Thank you

**Comment by AkshayaAcharya** [comment] 2020-10-18 10:05
@pavanchow 

During this COVID -19 pandemic period, Strength of Materials Lab is widely used and we are making few modifications in this lab.
I hope this would be the last update. 

I would request you to host the following version of the lab:

GitHub repo link: [https://github.com/virtual-labs/strength-of-materials-nitk](https://github.com/virtual-labs/strength-of-materials-nitk)
Branch: Master
Tag: v1.1.5
URL of Lab: [http://sm-nitk.vlabs.ac.in/](http://sm-nitk.vlabs.ac.in/)

Thank you

**Comment by pavanchow** [comment] 2020-10-19 04:08
@AkshayaAcharya
Hosted URL of Lab: http://sm-nitk.vlabs.ac.in
Branch: Master
Tag: v1.1.5

Please check and confirm.

**Comment by AkshayaAcharya** [comment] 2020-10-19 06:31
@pavanchow 

Contents are updated.

Thank you

**Comment by AkshayaAcharya** [comment] 2020-11-05 06:40
@pavanchow

Contents of Strength of Materials Lab has been uploaded. Below is repository link:
https://github.com/virtual-labs/strength-of-materials-nitk.git

Commit Version: v1.1.6

I would request you to upload the new content and re-host the link http://sm-nitk.vlabs.ac.in/

Thank you

**Comment by pavanchow** [comment] 2020-11-05 07:28
@AkshayaAcharya
Hosted URL of Lab: http://sm-nitk.vlabs.ac.in
Branch: Master
Tag: v1.1.6

Please check and confirm.

**Comment by AkshayaAcharya** [comment] 2020-11-05 09:56
@pavanchow 

Contents are updated

Thank you

**Comment by SOLVE-NITK** [comment] 2021-08-10 11:44
@pavanchow 

Permission to virtual-labs/strength-of-materials-nitk.git is denied to SOLVE-NITK.

Please grant access to [https://github.com/virtual-labs/strength-of-materials-nitk.git/](https://github.com/virtual-labs/strength-of-materials-nitk.git/)

Thank you

**Comment by pavanchow** [comment] 2021-08-10 11:53
@SOLVE-NITK sent an invite to edit the mentioned repository. Please click on the link and accept: https://github.com/virtual-labs/strength-of-materials-nitk/invitations

**Comment by SOLVE-NITK** [comment] 2021-08-10 12:03
@pavanchow 

Strength of Material Lab contents are updated. Below are the details:

Github repo link: [https://github.com/virtual-labs/strength-of-materials-nitk.git
](https://github.com/virtual-labs/strength-of-materials-nitk.git)
Branch: Master
Tag: v1.1.7
URL of Lab: http://sm-nitk.vlabs.ac.in


Please update the Lab.


Thank you

**Comment by pavanchow** [comment] 2021-08-10 15:16
@SOLVE-NITK 
Hosted URL of Lab: https://sm-nitk.vlabs.ac.in
Branch: Master
Tag: v1.1.7

Please check and confirm.

**Comment by SOLVE-NITK** [comment] 2021-08-11 04:42
@pavanchow 

Contents are updated. Thank you

**Comment by SOLVE-NITK** [comment] 2021-12-06 04:31
@pavanchow 

**Repository Creation Request**

**Coordinating Institute**: NITK Surathkal
**Approver’s Name**: Dr. Pruthviraj U, NITK Surathkal (Email: pruthviu@nitk.edu.in )

**Approved Proposal**: The list of experiments for Strength of Materials Lab are as follows:
1. Izod Impact Test
2. Charpy Impact Test
3. Direct Shear Test on Mild Steel Rod
4. Direct Shear Test on Timber Specimen
5. Direct Shear Test on Mild Steel Plate
6. Brinell Hardness Test
7. Bending Test on Mild Steel
8. Rockwell Hardness Test
9. Vickers Hardness Test
10. Tensile Test on Mild Steel
11. Tensile Test on Cast Iron
12. Compression Test on Mild Steel
13. Compression Test on Cast Iron
14. Torsion Test on Mild Steel
 
**Hosted URL**: https://sm-nitk.vlabs.ac.in/

**Primary GitHub Handle Details**:
Virtual Labs
Username: @SOLVE-NITK
Gmail: csd@nitk.edu.in

**Secondary GitHub Handle Details**:
Akshaya
Username: @AkshayaAcharya
Gmail: acharya.akshaya04@gmail.com
 
Anusha B Salian
Username: @AnushaSalian
Gmail: saliananusha1994@gmail.com


Thank you

**Comment by pavanchow** [comment] 2021-12-06 09:01
@AnushaSalian Please a new issue for "Repository Creation". Please use this issue for hosting related issues.

**Comment by SOLVE-NITK** [comment] 2021-12-27 05:26
**Request to rehost the experiments of Lab: Strength of Materials Lab** : 
Lab URL: (https://sm-nitk.vlabs.ac.in/)

**Experiment Name** | **Experiment Source Repo link** | **Tag**

1. Izod Impact Test  | https://github.com/virtual-labs/exp-izod-impact-test-nitk | v1.0.1
2. Charpy Impact Test - https://github.com/virtual-labs/exp-charpy-impact-test-nitk | v1.0.1
3. Direct Shear Test on Mild Steel Rod - https://github.com/virtual-labs/exp-direct-shear-test-steel-rod-nitk | v1.0.0
4. Direct Shear Test on Timber Specimen - https://github.com/virtual-labs/exp-direct-shear-test-timber-nitk | v1.0.0
5. Direct Shear Test on Mild Steel Plate - https://github.com/virtual-labs/exp-direct-shear-test-steel-plate-nitk | v1.0.0
6. Brinell Hardness Test - https://github.com/virtual-labs/exp-brinell-hardness-test-nitk | v1.0.1
7. Bending Test on Mild Steel - https://github.com/virtual-labs/exp-bending-test-mild-steel-nitk | v1.0.0
8. Rockwell Hardness Test - https://github.com/virtual-labs/exp-rockwell-hardness-test-nitk | v1.0.0
9. Vickers Hardness Test - https://github.com/virtual-labs/exp-vickers-hardness-test-nitk | v1.0.0
10. Tensile Test on Mild Steel - https://github.com/virtual-labs/exp-tensile-test-mild-steel-nitk | v1.0.0
11. Tensile Test on Cast Iron - https://github.com/virtual-labs/exp-tensile-test-cast-iron-nitk | v1.0.0
12. Compression Test on Mild Steel - https://github.com/virtual-labs/exp-compression-test-mild-steel-nitk | v1.0.0
13. Compression Test on Cast Iron - https://github.com/virtual-labs/exp-compression-test-cast-iron-nitk | v1.0.0
14. Torsion Test on Mild Steel - https://github.com/virtual-labs/exp-torsion-test-mild-steel-nitk | v1.0.0

Thank you
@pavanchow

**Comment by SOLVE-NITK** [comment] 2021-12-27 05:28
**Request to edit sections of Strength of Materials Lab** 
**Lab URL**: (https://sm-nitk.vlabs.ac.in/)


**Lab Section Name** - **New content**
**Introduction**: 

The strength of the material is the body of knowledge that deals with the relation between internal forces, deformations and external loads, etc. This laboratory provides the basic knowledge of the strength of materials and here, the students can perform different tests on different materials.
Click on the List of experiments to see which are the labs available to explore.

**Target Audience**: 
This course is primarily for pre-final and/or final year students of Bachelor's course in civil Engineering. This course is also useful for diploma in Civil Engineering students.


**Courses Alignment**: 
Following are the courses in which one can come across the theory connected to the experiments in this lab

- Strength of Materials
- Mechanics Material

Thank you
@pavanchow

**Comment by pavanchow** [comment] 2021-12-27 05:33
@SOLVE-NITK 

Please provide the "Objective" of the lab.

**Comment by SOLVE-NITK** [comment] 2021-12-27 05:42
**Request to edit sections of Strength of Materials Lab**
**Lab URL**: (https://sm-nitk.vlabs.ac.in/)

**Lab Section Name** - **New content**
**Introduction**:
Welcome to Strength of Materials Lab. The strength of the material is the body of knowledge that deals with the relation between internal forces, deformations and external loads, etc. 

**Objective**: 
This laboratory provides the basic knowledge of the strength of materials and here, the students can perform different tests on different materials.


Thank you
@pavanchow

**Comment by pavanchow** [comment] 2021-12-27 08:52
@SOLVE-NITK
Hosted Strength of Materials Lab
URL of Lab: https://sm-nitk.vlabs.ac.in with updated sources
Branch: Master

Please check and confirm.

**Comment by SOLVE-NITK** [comment] 2021-12-28 03:18
@pavanchow 

Except for 2 experiments, the contents of other experiments are updated.

**Below are the details**:
**Experiment Name** | **Experiment Source Repo link** | **Tag**

Izod Impact Test | https://github.com/virtual-labs/exp-izod-impact-test-nitk | v1.0.1
Charpy Impact Test - https://github.com/virtual-labs/exp-charpy-impact-test-nitk | v1.0.1

Thank you

**Comment by SOLVE-NITK** [comment] 2021-12-30 05:06
@pavanchow 

Contents of the below experiments are not updated.

Below are the details:
**Experiment Name** | **Experiment Source Repo link** | **Tag**

Izod Impact Test | https://github.com/virtual-labs/exp-izod-impact-test-nitk | v1.0.1
Charpy Impact Test - https://github.com/virtual-labs/exp-charpy-impact-test-nitk | v1.0.1

Can you please fix the issue?

Thank you

**Comment by pavanchow** [comment] 2021-12-30 05:31
@SOLVE-NITK
Hosted Strength of Materials Lab with mentioned experiments
URL of Lab: https://sm-nitk.vlabs.ac.in with updated sources
Branch: Master

Please check and confirm.

**Comment by SOLVE-NITK** [comment] 2021-12-30 06:08
@pavanchow 

Contents are updated.

Thank you

**Comment by SOLVE-NITK** [comment] 2021-12-31 06:11
@pavanchow 

Requesting to edit the below sections of the lab: https://sm-nitk.vlabs.ac.in/

**Target Audience**:
UG 
B.E/ B.Tech in Civil Engineering or Mechanical Engineering
Diploma in Civil Engineering or Mechanical Engineering

PG
M.Tech/ MS  in Structural Engineering or Earthquake Engineering or Material Engineering 

**Course Alignment**:
Following are the courses in which one can come across the theory connected to the experiments in this lab :

Strength of materials - National Institute of Technology Karnataka Surathkal, Visvesvaraya Technological University, Anna University, Vellore Institute of Technology
Building Materials Testing Laboratory - Visvesvaraya Technological University
Mechanics of Materials - Goa University
Strength of Materials Laboratory - Anna University 
Structural mechanics -Ⅰ- Jadavpur University
Structural Mechanics -ⅠⅠ - Jadavpur University

Thank you

**Comment by pavanchow** [comment] 2021-12-31 08:16
@SOLVE-NITK
Hosted Strength of Materials Lab with updated lab content
URL of Lab: https://sm-nitk.vlabs.ac.in with updated sources
Branch: Master

Please check and confirm.

**Comment by SOLVE-NITK** [comment] 2021-12-31 13:48
@pavanchow 

Contents are updated. Thank you

**Comment by SOLVE-NITK** [comment] 2021-12-31 13:55
@pavanchow 

Please update the contents of the below experiments.

Lab URL: https://sm-nitk.vlabs.ac.in/

Below are the details:
**Experiment Name** | **Experiment Source Repo link** | **Tag**


1. Direct Shear Test on Mild Steel Rod - https://github.com/virtual-labs/exp-direct-shear-test-steel-rod-nitk | v1.0.1
2. Direct Shear Test on Timber Specimen - https://github.com/virtual-labs/exp-direct-shear-test-timber-nitk | v1.0.1
3. Direct Shear Test on Mild Steel Plate - https://github.com/virtual-labs/exp-direct-shear-test-steel-plate-nitk | v1.0.1
4. Tensile Test on Mild Steel - https://github.com/virtual-labs/exp-tensile-test-mild-steel-nitk | v1.0.1
5. Tensile Test on Cast Iron - https://github.com/virtual-labs/exp-tensile-test-cast-iron-nitk | v1.0.1
6. Compression Test on Mild Steel - https://github.com/virtual-labs/exp-compression-test-mild-steel-nitk | v1.0.1
7. Compression Test on Cast Iron - https://github.com/virtual-labs/exp-compression-test-cast-iron-nitk | v1.0.1
8. Torsion Test on Mild Steel - https://github.com/virtual-labs/exp-torsion-test-mild-steel-nitk | v1.0.1

Thank you

**Comment by pavanchow** [comment] 2022-01-03 03:53
@SOLVE-NITK
Hosted Strength of Materials Lab with updated experiments
URL of Lab: https://sm-nitk.vlabs.ac.in with updated sources
Branch: Master

Please check and confirm.

**Comment by SOLVE-NITK** [comment] 2022-01-04 05:49
@pavanchow 

Contents are updated. Thank you

**Closed** 2024-12-05 11:05 UTC
Labels: Phase-2, Hosting Request

**Comment by ravikiran2020** [comment] 2024-12-05 14:22
@SOLVE-NITK Lab is rehosted with updates. 
Please check.
