### ISSUE TITLE
Virtual Microwave lab dei test failed on ADS

### ISSUE THREAD

**Issue by samodk** [Virtual-Labs/engineers-forum#157] opened 2015-07-04 06:29 UTC
Hi
When i run the lab on ADS, It get failed with showing the following error: I think it is not able to create VM. Plz check once ...

I 150702 15:36:52 sh:382] <Command '/bin/ping 49.50.96.7...(6 more)' call_args {'bg': False, 'timeo...(476 more)>: starting process
[D 150702 15:36:55 BaseAdapter:26] cant ping!
[D 150702 15:36:55 CentOSVZAdapter:79] CentOSVZAdapter: create_vm(): ip = 49.50.96.73, vm_id = 9673, vm_create_args =  --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 49.50.96.73 --diskspace 10G:15.0G --hostname microwave lab.vlabs.ac.in, vm_set_args =  --nameserver inherit --ram 256M --swap 512M --onboot yes --save
[D 150702 15:36:55 CentOSVZAdapter:86] CentOSVZAdapter: create_vm(): create command = ssh -o "StrictHostKeyChecking no" root@49.50.96.72 "/usr/sbin/vzctl create 9673  --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 49.50.96.73 --diskspace 10G:15.0G --hostname microwave lab.vlabs.ac.in"
[D 150702 15:36:55 execute_commands:27] command: ssh -o "StrictHostKeyChecking no" root@49.50.96.72 "/usr/sbin/vzctl create 9673  --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 49.50.96.73 --diskspace 10G:15.0G --hostname microwave lab.vlabs.ac.in"
Address 49.50.96.72 maps to 49-50-96-72.isp.nstpl.com, but this does not map back to the address - POSSIBLE BREAK-IN ATTEMPT!
Invalid extra arguments: lab.vlabs.ac.in 
[E 150702 15:36:58 execute_commands:34] Called Process Error: Command 'ssh -o "StrictHostKeyChecking no" root@49.50.96.72 "/usr/sbin/vzctl create 9673  --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 49.50.96.73 --diskspace 10G:15.0G --hostname microwave lab.vlabs.ac.in"' returned non-zero exit status 20
[E 150702 15:36:58 CentOSVZAdapter:113] Error creating VM: Command 'ssh -o "StrictHostKeyChecking no" root@49.50.96.72 "/usr/sbin/vzctl create 9673  --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 49.50.96.73 --diskspace 10G:15.0G --hostname microwave lab.vlabs.ac.in"' returned non-zero exit status 20
[D 150702 15:36:58 AdapterServer:57] success status returned False from create_vm
[D 150702 15:36:58 AdapterServer:61] result = Failed while creating VM
[E 150702 15:36:58 web:1908] 500 POST /api/1.0/vm/create (127.0.0.1) 8813.09ms
[D 150702 15:36:58 VMPool:87] VMPool: create_vm(): Response text from adapter: Failed while creating VM
[E 150702 15:36:58 VMPool:96] VMPool: create_vm(): Error communicating with adapter: VMPool: create_vm(): Error creating VM: Failed while creating VM
[E 150702 15:36:58 Controller:55] test_lab(): Test failed with error: VMPool: create_vm(): Error creating VM: VMPool: create_vm(): Error creating VM: Failed while creating VM
[I 150702 15:36:58 web:1908] 200 POST / (127.0.0.1) 1853133.88ms
[W 150702 15:36:58 web:1908] 404 GET http://zc.qq.com/cgi-bin/common/attr?id=260714&r=0.3246744788553388 (115.230.127.237) 1.78ms
[W 150702 15:39:47 web:1908] 404 POST http://123.249.24.233/POST_ip_port.php (222.186.129.5) 0.73ms

**Comment by sivashankerN** [comment] 2015-07-13 06:37
Hello Samod,
Please check following
1. Disk space ? (command to check disk space is df -h). Is there free space more than 16GB?
2.  iptables -nL (If any rules are present flush them form now by running iptables -F)
then try to deploy again.

**Comment by samodk** [comment] 2015-07-14 06:50
ok  thanks 
Let me check  and then i will let u know..

**Comment by sanchita-dixit** [comment] 2015-07-21 06:32
@samodk Any updates on this.

**Comment by samodk** [comment] 2015-07-21 07:08
Hi Shiva i have checked the above command , and there is no any space issue....

i request you to plz check the following URL :

**Comment by samodk** [comment] 2015-07-21 07:41
This is the source path:  virtual-microwave-laboratory-dei/src/lab/includes/config_file.php
I think the error is with the hostiing URL: Earlier this lab is forging the developer URL, this issue was discussed with Anon and Jayanth. Below URL is not able to create the the VM.

<?php
set_time_limit(0);
define('DB_HOST','localhost');
define('DB_USER','sandeep4_user');
define('DB_PASSWORD','p@ssword12345');
define('DB_DATABASE','sandeep4_virtual');
define('DB_TYPE','mysql');
define('CONNECTION_TYPE','normal'); //persist
define('USE_MAILER','SENDMAIL');
define('SMTP_SERVER','smtp.gmail.com');
define('SMTP_USERNAME','developer.cool@gmail.com');
define('SMTP_PASSWORD','ns7679');
define('SMTP_SECURITY','tls');
define('SMTP_PORT',465);
define('TABLE_PREFIX','');
define('SESSION_PREFIX','IEE_');
define('SERVER_URL','http://mw-dei.virtual-lab.dei.ac.in');
define('APP_FOL','/projects/virtual_labs/');
define('DB_SESSION',false);
define('APP_NAME','Virtual Labs');
?>

**Comment by ecthiender** [comment] 2015-07-22 04:58
@samodk if you look at the above error logs properly, and try to observe where the error message is, you should be able to see:

Called Process Error: Command 'ssh -o "StrictHostKeyChecking no" root@49.50.96.72 "/usr/sbin/vzctl create 9673 --ostemplate ubuntu-12.04-custom-x86_64 --ipadd 49.50.96.73 --diskspace 10G:15.0G --hostname microwave lab.vlabs.ac.in"' returned non-zero exit status 20


Now if you look at the above message, and specifically the command again, and notice the "--hostname" part, you should be able to see the command is: `--hostname mircowave lab.vlabs.ac.in`

I guess now you realize the error! Hostnames cannot have space, and hence this command takes hostname as "mircowave" and the rest of part "lab.vlabs.ac.in" is extra argument, which the command does not understand, and hence VM creation fails.

If you notice further, it gives this error message: `Invalid extra arguments: lab.vlabs.ac.in`

I think the space comes, because you the `lab id` you are giving in the OVPL's test a lab page, contains a space. Can you try the same deployment without any space in the `lab_id` , and see if this error happens?

If it resolves the issue, please close this ticket.

**Comment by ecthiender** [comment] 2015-07-28 13:26
@samodk did the above help?

**Comment by ecthiender** [comment] 2015-08-07 06:09
@samodk did the above resolve your issue?

**Comment by ecthiender** [comment] 2015-08-11 04:53
@samodk request you to comment

**Comment by samodk** [comment] 2015-08-26 08:51
Hi Anon 
Sorry for the late reply...
 We r facing some network issue here.I m still getting the same error...I remove the space in the lab id, but it do not fix up the issue it is showing the same error..

**Comment by samodk** [comment] 2015-09-07 05:42
Hello 
Can you plz check this lab and tell me the possible solutions..
Or if possible the respective lab developer can check whats the issue.... He may go for remote access. and solve the bug...Give me the reply.....
Thanks

**Comment by ecthiender** [comment] 2015-09-10 08:31
When you removed the space from `lab_id` what is the error that you are getting?

Can you paste the error log?

**Comment by samodk** [comment] 2015-09-11 09:01
Hi Anon
 This is the error log :  
Warning: require_once(/var/www/projects/virtual_labs/includes/functions.php): failed to open stream: No such file or directory in /var/www/includes/startup.php on line 73 Fatal error: require_once(): Failed opening required '/var/www/projects/virtual_labs/includes/functions.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/includes/startup.php on line 73

**Comment by ecthiender** [comment] 2015-09-11 11:28
@samodk This is not any ADS error. This is an application error! So, presumably, the problem is with the lab.

**Comment by samodk** [comment] 2015-09-12 05:31
yah thats right..
I asked the respective lab developer for the changes.. He made the required changes in the config_file.php. Now we need to test our lab on ADS.
Very soon i will let u know the status of lab..

**Closed** 2015-09-12 05:52 UTC
Labels: auto deployment, help wanted
