### ISSUE TITLE
https issue

### ISSUE THREAD

**Issue by sruthimangala** [Virtual-Labs/engineers-forum#29] opened 2015-03-07 06:36 UTC
We are not able to clone from a https github repo. We tried to run  the container using --no-check-certificate flag, but it is not working from ovpl.

[D 150307 11:57:12 LabManager:49] LabManager, clone_repo(): clone_cmd = ['git', 'clone', 'https://github.com/Virtual-Labs/population-ecology-virtual-lab-i-au.git', '--no-check-certificate', '/root/labs/lab-repo-cache/poe12population-ecology-virtual-lab-i-au.git', '--no-check-certificate']
[E 150307 11:57:12 LabManager:54] LabManager: clone_repo(): git clone failed: poe12population-ecology-virtual-lab-i-au.git --no-check-certificate Command '['git', 'clone', 'https://github.com/Virtual-Labs/population-ecology-virtual-lab-i-au.git', '--no-check-certificate', '/root/labs/lab-repo-cache/poe12population-ecology-virtual-lab-i-au.git', '--no-check-certificate']' returned non-zero exit status 129

**Comment by ecthiender** [comment] 2015-03-12 10:16
duplicate of #28

**Closed by ecthiender** 2015-03-12 10:16 UTC
