### ISSUE TITLE
Experiment Repository Creation Request for Probability and Statistics Lab - IITD

### ISSUE THREAD

**Issue by vlabsdev-iitd** [virtual-labs/engineers-forum#848] opened 2022-12-02 09:55 UTC
## *Repository Creation Request*
Use this to get your experiment repository created or updated on GitHub under Virtual Labs organization.

1. #### Coordinating Institute: IIT Delhi

2. #### Approver’s Name: IITD

3. #### Approved Proposal: [Probability and Statistics Lab.pdf](https://github.com/virtual-labs/engineers-forum/files/10139037/Probability.and.Statistics.Lab.pdf)

4. #### Hosted url: Not hosted 

5. #### Primary GitHub Handle Details:
   ##### Name: Virtual Labs IIT Delhi
   ##### GitHub Handle: vlabsdev-iitd
   ##### Email id: [vlabsdev.iitd@gmail.com](mailto:vlabsdev.iitd@gmail.com)

6. #### Secondary GitHub Handle Details:
   ##### Name: Prof. S. Dharmaraja
   ##### GitHub Handle: dharmarajas
   ##### Email id: [dharmar@maths.iitd.ac.in](mailto:dharmar@maths.iitd.ac.in)

   ##### Name: Ms. Anisha
   ##### GitHub Handle: virtuallabqueue
   ##### Email id: [anishaaggarwal7895@gmail.com](mailto:anishaaggarwal7895@gmail.com)
                     [maz188445@iitd.ac.in](mailto:maz188445@iitd.ac.in)

**Comment by pavanchow** [comment] 2022-12-02 10:09
@vlabsdev-iitd Repositories for Probability and Statistics are created on Oct 3. Please find links in the below comment, 

https://github.com/virtual-labs/engineers-forum/issues/804#issuecomment-1265438961

**Comment by priya100raman** [comment] 2023-10-09 04:29
Closing this issue since it is a duplicate of #804

**Closed by priya100raman** 2023-10-09 04:29 UTC
Labels: create experiment repos, Extended-Phase-3
